import Foundation
import NardukMusicCore
import NardukMusicDSP

/// A scripted signal timeline for the offline renderer and the `narduk-music` CLI, as JSON.
///
/// Signals can be listed one by one (`signals`) or generated by `segments`: a segment repeats a signal every
/// `every` seconds from `from` to `to`, with its level ramping linearly and its cues taken in turn. Actions change the
/// genre or queue a drop at a time.
///
/// ```json
/// {
///   "seed": 24301, "genre": "dubstep", "seconds": 30,
///   "segments": [
///     { "from": 0, "to": 10, "every": 0.25, "level": [0.1, 0.7], "levelLabel": "CPU",
///       "cues": [{ "gesture": "spark", "label": "swiftc" }], "cueEvery": 4 }
///   ],
///   "actions": [{ "time": 20, "queueDrop": true }]
/// }
/// ```
///
/// `notes` plays the guitars (`acousticGuitar`, `electricGuitar`, `bassGuitar`, `strum`, `electricStrum`) directly,
/// beside whatever the conductor writes: each names an instrument, a time in seconds and a MIDI pitch. A time lands on
/// the nearest half of a 16th-note step.
///
/// ```json
/// { "seconds": 8, "conductor": false, "notes": [
///   { "time": 0.5, "instrument": "acousticGuitar", "pitch": 52, "length": 1.2 },
///   { "time": 2.0, "instrument": "electricStrum", "pitch": 45, "chord": "minor", "direction": "down" }
/// ] }
/// ```
public struct MusicScenario: Sendable, Hashable, Codable {
    /// A run of repeated signals.
    public struct Segment: Sendable, Hashable, Codable {
        public var from: Double
        public var to: Double
        /// Seconds between signals.
        public var every: Double
        /// The level at `from` and at `to`, interpolated linearly; nil sends no level.
        public var level: [Double]?
        /// Shown as "<levelLabel> NN%" when a level is set.
        public var levelLabel: String?
        public var flow: MusicFlow?
        /// Cues taken in turn, one per signal that carries cues.
        public var cues: [MusicCue]?
        /// Every Nth signal of the segment carries a cue (1 = every signal).
        public var cueEvery: Int?
        public var pan: Double?
        public var character: MusicCharacter?

        public init(
            from: Double, to: Double, every: Double, level: [Double]? = nil, levelLabel: String? = nil,
            flow: MusicFlow? = nil, cues: [MusicCue]? = nil, cueEvery: Int? = nil, pan: Double? = nil,
            character: MusicCharacter? = nil
        ) {
            self.from = from
            self.to = to
            self.every = every
            self.level = level
            self.levelLabel = levelLabel
            self.flow = flow
            self.cues = cues
            self.cueEvery = cueEvery
            self.pan = pan
            self.character = character
        }
    }

    /// Something done to the song at a time.
    public struct Action: Sendable, Hashable, Codable {
        public var time: Double
        public var genre: Genre?
        public var queueDrop: Bool?

        public init(time: Double, genre: Genre? = nil, queueDrop: Bool? = nil) {
            self.time = time
            self.genre = genre
            self.queueDrop = queueDrop
        }
    }

    /// A note for one of the guitars, in seconds rather than steps.
    public struct Note: Sendable, Hashable, Codable {
        /// Seconds from the start of the render.
        public var time: Double
        public var instrument: Instrument
        /// MIDI note number; a strum's chord root.
        public var pitch: Int
        /// Seconds the key is held (default 0.5).
        public var length: Double?
        /// 0 ... 1 (default 0.8).
        public var velocity: Double?
        /// -1 ... 1.
        public var pan: Double?
        /// Electric guitar drive, 0 ... 1.
        public var drive: Double?
        /// A strum's chord (default `major`).
        public var chord: StrumChord?
        /// A strum's direction (default `down`).
        public var direction: StrumStroke?

        public init(
            time: Double, instrument: Instrument, pitch: Int, length: Double? = nil, velocity: Double? = nil,
            pan: Double? = nil, drive: Double? = nil, chord: StrumChord? = nil, direction: StrumStroke? = nil
        ) {
            self.time = time
            self.instrument = instrument
            self.pitch = pitch
            self.length = length
            self.velocity = velocity
            self.pan = pan
            self.drive = drive
            self.chord = chord
            self.direction = direction
        }
    }

    public var name: String?
    public var seed: UInt64?
    public var genre: Genre?
    public var bpm: Double?
    /// The kind of music (nil: electronic, as before). `ambient` swaps the genre's arrangement for the swell and settle one.
    public var family: GenreFamily?
    /// How far the seed reaches beyond the genre's banks (nil: 0, the original songs). See `SongSettings.variety`.
    public var variety: Double?
    /// True takes the tempo from the seed, inside the genre's range (`SongSettings.varied`); `bpm` still wins.
    public var varied: Bool?
    /// Default length when the caller gives none.
    public var seconds: Double?
    /// Build and drop thresholds, when the source's level scale wants different ones from the defaults.
    public var buildThreshold: Double?
    public var dropThreshold: Double?
    public var signals: [MusicSignal]?
    public var segments: [Segment]?
    public var actions: [Action]?
    /// Notes for the guitars, played directly (see `Note`).
    public var notes: [Note]?
    /// False renders only `notes`: the conductor writes nothing. Nil or true leaves it playing.
    public var conductor: Bool?

    public init(
        name: String? = nil, seed: UInt64? = nil, genre: Genre? = nil, bpm: Double? = nil, family: GenreFamily? = nil,
        variety: Double? = nil, varied: Bool? = nil, seconds: Double? = nil,
        buildThreshold: Double? = nil, dropThreshold: Double? = nil, signals: [MusicSignal]? = nil,
        segments: [Segment]? = nil, actions: [Action]? = nil, notes: [Note]? = nil,
        conductor: Bool? = nil
    ) {
        self.name = name
        self.seed = seed
        self.genre = genre
        self.bpm = bpm
        self.family = family
        self.variety = variety
        self.varied = varied
        self.seconds = seconds
        self.buildThreshold = buildThreshold
        self.dropThreshold = dropThreshold
        self.signals = signals
        self.segments = segments
        self.actions = actions
        self.notes = notes
        self.conductor = conductor
    }

    /// Reads a scenario from JSON.
    public static func load(_ data: Data) throws -> MusicScenario {
        try JSONDecoder().decode(MusicScenario.self, from: data)
    }

    /// The song settings the scenario asks for, over `base`.
    public func settings(base: SongSettings = SongSettings()) -> SongSettings {
        var settings = base
        // Scenarios predate variety: unless one asks, the song is the original one for its seed.
        settings.variety = min(1, max(0, variety ?? 0))
        if let seed { settings.seed = seed }
        if let genre { settings.genre = genre }
        if varied == true {
            settings.bpm = SongSettings.varied(genre: settings.genre, seed: settings.seed).bpm
        }
        if let bpm { settings.bpm = bpm }
        if let family { settings.family = family }
        return settings
    }

    /// The notes as `ScheduledNote`s on the song's step grid, in time order. A time lands on the nearest half step
    /// (the second half as a swing `delay`), the resolution a `ScheduledNote` has.
    public func scheduledNotes(settings: SongSettings) -> [ScheduledNote] {
        let secondsPerStep = settings.secondsPerStep
        return (notes ?? []).filter { $0.time >= 0 && $0.time.isFinite }.sorted { $0.time < $1.time }.map { note in
            let halves = Int((note.time / secondsPerStep * 2).rounded())
            let isStrum = note.instrument == .strum || note.instrument == .electricStrum
            var params = NoteParams(
                pitch: note.pitch, lengthSteps: max(1, Int(((note.length ?? 0.5) / secondsPerStep).rounded(.up))),
                drive: note.drive, pan: note.pan ?? 0, delay: halves % 2 == 1 ? 0.5 : nil)
            if isStrum {
                params.voice = note.chord?.voice ?? 0
                params.formant = note.direction == .up ? 1 : 0
            }
            return ScheduledNote(
                step: halves / 2, instrument: note.instrument, velocity: note.velocity ?? 0.8, params: params)
        }
    }

    /// Every signal, listed and generated, in time order (stable for equal times: listed first, then segments).
    public func timeline() -> [MusicSignal] {
        var all = signals ?? []
        for segment in segments ?? [] where segment.every > 0 && segment.to > segment.from {
            let count = Int(((segment.to - segment.from) / segment.every).rounded(.up))
            let cueEvery = max(1, segment.cueEvery ?? 1)
            var cueIndex = 0
            for index in 0..<count {
                let time = segment.from + Double(index) * segment.every
                guard time < segment.to else { break }
                var signal = MusicSignal(
                    time: time, flow: segment.flow, pan: segment.pan ?? 0, character: segment.character)
                if let level = segment.level, let first = level.first {
                    let last = level.last ?? first
                    let fraction = count > 1 ? Double(index) / Double(count - 1) : 0
                    let value = first + (last - first) * fraction
                    signal.level = value
                    if let label = segment.levelLabel {
                        signal.levelLabel = "\(label) \(Int((value * 100).rounded()))%"
                    }
                }
                if let cues = segment.cues, !cues.isEmpty, index % cueEvery == 0 {
                    signal.cues = [cues[cueIndex % cues.count]]
                    cueIndex += 1
                }
                all.append(signal)
            }
        }
        return all.enumerated().sorted { ($0.element.time, $0.offset) < ($1.element.time, $1.offset) }.map(\.element)
    }
}

extension OfflineRenderer {
    /// Renders `seconds` of a scenario. A signal is delivered in the tick during which its time falls; actions apply
    /// at the start of the tick that contains them.
    public static func render(
        _ scenario: MusicScenario, seconds: Double? = nil, base: SongSettings = SongSettings(),
        sampleRate: Double = 48_000, progress: ((Double) -> Void)? = nil
    ) -> RenderedAudio {
        let renderer = OfflineRenderer(
            settings: scenario.settings(base: base), sampleRate: sampleRate, playsConductor: scenario.conductor != false
        )
        renderer.schedule(scenario.scheduledNotes(settings: renderer.settings))
        if let build = scenario.buildThreshold {
            renderer.setThresholds(build: build, drop: scenario.dropThreshold ?? build * 0.7)
        }
        let length = seconds ?? scenario.seconds ?? 30
        let ticks = Int((length * tickRate).rounded())
        var signals = scenario.timeline()[...]
        var actions = (scenario.actions ?? []).sorted { $0.time < $1.time }[...]
        var left: [Float] = []
        var right: [Float] = []
        left.reserveCapacity(ticks * renderer.framesPerTick)
        right.reserveCapacity(ticks * renderer.framesPerTick)
        for tick in 0..<ticks {
            let now = Double(tick) / tickRate
            let end = Double(tick + 1) / tickRate
            while let action = actions.first, action.time < end {
                if let genre = action.genre { renderer.setGenre(genre) }
                if action.queueDrop == true { renderer.queueDrop() }
                actions = actions.dropFirst()
            }
            var arrived: [MusicSignal] = []
            while let signal = signals.first, signal.time < end {
                arrived.append(signal)
                signals = signals.dropFirst()
            }
            let audio = renderer.advance(signals: arrived)
            left += audio.left
            right += audio.right
            if let progress, tick % 60 == 59 { progress(now + 1 / tickRate) }
        }
        return RenderedAudio(sampleRate: sampleRate, left: left, right: right)
    }
}
