import Foundation

/// Reads the per-run rows the scorecard wrote and produces `scores.csv` and the readable `scores.md`.
enum ScorecardReport {
    /// The score columns, in file order.
    static let columns: [(key: String, value: @Sendable (VisualScorecard.Metrics) -> Double)] = [
        ("frames", { Double($0.frames) }),
        ("luma_p10", { $0.luma.p10 }), ("luma_p50", { $0.luma.p50 }), ("luma_p90", { $0.luma.p90 }),
        ("spread_p10", { $0.spread.p10 }), ("spread_p50", { $0.spread.p50 }), ("spread_p90", { $0.spread.p90 }),
        ("kick_hits", { Double($0.kickHits) }), ("kick_ratio", { $0.kickRatio }), ("kick_lag_ms", { $0.kickLagMS }),
        ("snare_hits", { Double($0.snareHits) }), ("snare_ratio", { $0.snareRatio }),
        ("snare_lag_ms", { $0.snareLagMS }),
        ("corr_rms_luma", { $0.rmsLumaCorrelation }), ("corr_rms_motion", { $0.rmsMotionCorrelation }),
        ("section_motion_ratio", { $0.sectionMotionRatio }), ("section_luma_ratio", { $0.sectionLumaRatio }),
        ("frozen_share", { $0.frozenShare }), ("motion_p50", { $0.motionP50 }), ("motion_p99", { $0.motionP99 }),
    ]

    static let leading = ["song", "transform", "visualizer", "title", "window_start_s"]
    static var header: String { (leading + columns.map(\.key) + ["flags"]).joined(separator: ",") }

    static func number(_ value: Double) -> String { value.isNaN ? "nan" : String(format: "%.5f", value) }

    static func rowLine(
        song: String, transform: String, id: String, title: String, start: Double, m: VisualScorecard.Metrics
    ) -> String {
        let values = columns.map { number($0.value(m)) }
        return ([song, transform, id, title, String(format: "%.1f", start)] + values + [VisualScorecard.flags(m)])
            .joined(separator: ",")
    }

    struct Row {
        var song: String
        var transform: String
        var id: String
        var title: String
        var start: Double
        var values: [String: Double]
        var flags: String

        subscript(key: String) -> Double { values[key] ?? .nan }
    }

    static func rows(in directory: URL) throws -> [Row] {
        let names = try FileManager.default.contentsOfDirectory(atPath: directory.path).filter { $0.hasSuffix(".csv") }
        let keys = columns.map(\.key)
        var out: [Row] = []
        for name in names.sorted() {
            let text = try String(contentsOf: directory.appendingPathComponent(name), encoding: .utf8)
            for line in text.split(separator: "\n") {
                let cells = line.split(separator: ",", omittingEmptySubsequences: false).map(String.init)
                guard cells.count == leading.count + keys.count + 1 else { continue }
                var values: [String: Double] = [:]
                for (i, key) in keys.enumerated() { values[key] = Double(cells[leading.count + i]) ?? .nan }
                out.append(
                    Row(
                        song: cells[0], transform: cells[1], id: cells[2], title: cells[3],
                        start: Double(cells[4]) ?? 0, values: values, flags: cells.last ?? ""))
            }
        }
        return out
    }

    /// Gallery order is the order the rows are written in; sort by song, transform (identity first), then id.
    static func write(rowsDirectory: URL, to directory: URL, order ids: [String]) throws {
        let all = try rows(in: rowsDirectory)
        let order = Dictionary(uniqueKeysWithValues: ids.enumerated().map { ($1, $0) })
        let sorted = all.sorted {
            if $0.song != $1.song { return $0.song < $1.song }
            if $0.transform != $1.transform { return $0.transform == "identity" }
            return (order[$0.id] ?? 999) < (order[$1.id] ?? 999)
        }
        var csv = header + "\n"
        for row in sorted {
            let numbers = columns.map { number(row[$0.key]) }
            csv +=
                ([row.song, row.transform, row.id, row.title, String(format: "%.1f", row.start)] + numbers + [row.flags])
                .joined(separator: ",") + "\n"
        }
        try csv.write(to: directory.appendingPathComponent("scores.csv"), atomically: true, encoding: .utf8)
        try markdown(sorted).write(to: directory.appendingPathComponent("scores.md"), atomically: true, encoding: .utf8)
    }

    // MARK: Markdown

    static func f(_ v: Double, _ digits: Int = 2) -> String { v.isNaN ? "-" : String(format: "%.\(digits)f", v) }

    static func markdown(_ rows: [Row]) -> String {
        var md = "# Visualizer scorecard\n\n"
        md += "Generated by `VisualScorecardRunTests` (docs/visual-scorecard.md). Numbers: luma and spread are 0 to 1; "
        md += "`kick x` and `snare x` are the mean motion in the 100 ms after a hit over the mean motion elsewhere "
        md += "(above 1 reacts), `lag` the ms at which the hit-aligned motion peaks; `r rms` the correlation of 0.5 s "
        md += "smoothed rms with luma and with motion; `sect x` the motion in the loudest 20% of 2 s windows over the "
        md += "quietest 20%; `frozen` the share of frames with near-zero motion; `p99 mot` the 99th percentile "
        md += "motion (strobing). `-` is not computable (too few hits, or a flat series).\n\n"
        let songs = Array(Set(rows.map(\.song))).sorted()
        let transforms = ["identity"] + Array(Set(rows.map(\.transform)).subtracting(["identity"])).sorted()
        for song in songs {
            for transform in transforms {
                let subset = rows.filter { $0.song == song && $0.transform == transform }
                guard let first = subset.first else { continue }
                md += "## \(song), \(transform) (window from \(f(first.start, 1)) s, "
                md += "\(f(first["kick_hits"], 0)) kick and \(f(first["snare_hits"], 0)) snare hits in it)\n\n"
                md +=
                    "| Visualizer | luma p10/p50/p90 | spread p10/p50/p90 | kick x | lag ms | snare x | lag ms | r rms-luma | r rms-motion | sect x motion | sect x luma | frozen | p50 mot | p99 mot | flags |\n"
                md += "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n"
                for r in subset {
                    md += "| \(r.title) | \(f(r["luma_p10"])) / \(f(r["luma_p50"])) / \(f(r["luma_p90"])) "
                    md += "| \(f(r["spread_p10"])) / \(f(r["spread_p50"])) / \(f(r["spread_p90"])) "
                    md +=
                        "| \(f(r["kick_ratio"])) | \(f(r["kick_lag_ms"], 0)) | \(f(r["snare_ratio"])) | \(f(r["snare_lag_ms"], 0)) "
                    md += "| \(f(r["corr_rms_luma"])) | \(f(r["corr_rms_motion"])) "
                    md += "| \(f(r["section_motion_ratio"])) | \(f(r["section_luma_ratio"])) "
                    md +=
                        "| \(f(r["frozen_share"] * 100, 0))% | \(f(r["motion_p50"], 4)) | \(f(r["motion_p99"], 4)) | \(r.flags) |\n"
                }
                md += "\n"
            }
        }
        md += worst(rows.filter { $0.transform == "identity" })
        md += compare(rows)
        return md
    }

    /// The five worst per metric, for each song, on the identity transform.
    static func worst(_ rows: [Row]) -> String {
        var md = "## Worst five per metric (identity)\n\n"
        let metrics: [(String, String, Bool)] = [
            ("Lowest kick response (x)", "kick_ratio", true), ("Lowest snare response (x)", "snare_ratio", true),
            ("Weakest loudness tracking (r rms-motion)", "corr_rms_motion", true),
            ("Weakest section contrast (motion x)", "section_motion_ratio", true),
            ("Most frozen frames", "frozen_share", false), ("Strongest strobing (p99 motion)", "motion_p99", false),
            ("Narrowest luma range (p90-p10)", "luma_range", true), ("Darkest (luma p50)", "luma_p50", true),
            ("Brightest (luma p50)", "luma_p50", false),
        ]
        for song in Array(Set(rows.map(\.song))).sorted() {
            md += "### \(song)\n\n"
            let subset = rows.filter { $0.song == song }
            for (title, key, ascending) in metrics {
                func value(_ r: Row) -> Double { key == "luma_range" ? r["luma_p90"] - r["luma_p10"] : r[key] }
                let ranked = subset.filter { !value($0).isNaN && !(key == "frozen_share" && value($0) < 0.0005) }.sorted
                {
                    ascending ? value($0) < value($1) : value($0) > value($1)
                }.prefix(5)
                let cells = ranked.map { "\($0.title) \(f(value($0), key == "frozen_share" ? 3 : 2))" }
                md += "- \(title): \(cells.joined(separator: "; "))\n"
            }
            md += "\n"
        }
        return md
    }

    /// Identity against rescale: the per-visualizer change in the headline numbers, and the mean change.
    static func compare(_ rows: [Row]) -> String {
        guard rows.contains(where: { $0.transform == "rescale" }) else { return "" }
        var md = "## Identity vs rescale (rescale minus identity)\n\n"
        md +=
            "The rescale transform maps each spectrum band's p5 to 0 and p98 to 1 over the song. Positive is more.\n\n"
        let keys: [(String, String, Int)] = [
            ("luma p50", "luma_p50", 3), ("spread p50", "spread_p50", 3), ("kick x", "kick_ratio", 2),
            ("snare x", "snare_ratio", 2), ("r rms-motion", "corr_rms_motion", 2),
            ("sect x motion", "section_motion_ratio", 2), ("frozen", "frozen_share", 3),
        ]
        for song in Array(Set(rows.map(\.song))).sorted() {
            md += "### \(song)\n\n| Visualizer | " + keys.map(\.0).joined(separator: " | ") + " |\n"
            md += "|---|" + keys.map { _ in "---" }.joined(separator: "|") + "|\n"
            var sums = [Double](repeating: 0, count: keys.count)
            var counts = [Int](repeating: 0, count: keys.count)
            let identity = rows.filter { $0.song == song && $0.transform == "identity" }
            for base in identity {
                guard
                    let other = rows.first(where: { $0.song == song && $0.transform == "rescale" && $0.id == base.id })
                else { continue }
                var cells: [String] = []
                for (i, key) in keys.enumerated() {
                    let delta = other[key.1] - base[key.1]
                    cells.append(delta.isNaN ? "-" : String(format: "%+.\(key.2)f", delta))
                    if !delta.isNaN {
                        sums[i] += delta
                        counts[i] += 1
                    }
                }
                md += "| \(base.title) | " + cells.joined(separator: " | ") + " |\n"
            }
            let means = keys.indices.map {
                counts[$0] == 0 ? "-" : String(format: "%+.\(keys[$0].2)f", sums[$0] / Double(counts[$0]))
            }
            md += "| **mean** | " + means.map { "**\($0)**" }.joined(separator: " | ") + " |\n\n"
        }
        return md
    }
}
